name: BeYou CI/CD Pipeline

# Triggers: Run on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs: Define the CI/CD workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up JDK 21 (matches your app's requirement)
      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Updated from 17 to 21
          distribution: 'temurin'  # Eclipse Temurin (reliable JDK)

      # 3. Build with Maven (CI step)
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Skips tests per your original pipeline

      # 4. Build Docker Image (CD step)
      - name: Build Docker Image
        run: docker build -t beyou:version-1.0 .

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ravi445 # Securely stored in GitHub Secrets
          password: Docker123@  # Securely stored in GitHub Secrets

      # 6. Tag and Push Docker Image to Docker Hub
      - name: Tag and Push Docker Image
        run: |
          docker tag beyou:version-1.0 ravi445/beyou:version-1.0
          docker tag beyou:version-1.0 ravi445/beyou:latest
          docker push ravi445/beyou:version-1.0
          docker push ravi445/beyou:latest