name: BeYou CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#      - name: Build Docker Image
#        run: docker build -t beYou:${{ github.sha }} .
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ ravi445 }}
#          password: ${{ Docker123@ }}
#      - name: Push Docker Image
#        run: |
#          docker beYou:${{ github.sha }} ${{ ravi445 }}/beYou:${{ github.sha }}
#          docker beYou:${{ github.sha }} ${{ ravi445 }}/beYou:latest
#          docker push ravi445/beYou:${{ github.sha }}
#          docker push ravi445/beYou:latest
